name: Python Linter

on:
  push:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Python Linter
       uses: sunnysid3up/python-linter@master
       with:
         source: "."
         strict: high
